name: Build, Package, Deploy to AWS Lambda

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Solution
        run: dotnet restore BookLendingSolution.slnx

      - name: Build Solution
        run: dotnet build BookLendingSolution.slnx --configuration Release --no-restore

      - name: Publish Lambda Project
        run: |
          dotnet publish src/BookLendingSolution/BookLendingSolution.csproj \
            -c Release \
            -o ./publish
          cd publish
          zip -r ../booklendingsolution.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload ZIP to S3
        run: aws s3 cp booklendingsolution.zip s3://${{ secrets.S3_BUCKET }}/booklendingsolution.zip

      - name: Deploy CloudFormation
        run: |
          sed -i "s|{{S3_BUCKET}}|${{ secrets.S3_BUCKET }}|g" infrastructure/cloudformation/template.yaml
          
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation/template.yaml \
            --stack-name ${{ secrets.STACK_NAME }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

